### ISSUE TITLE
Incorrect return from suggest_requests

### ISSUE THREAD

**Issue by svivian** [arjunsuresh/qa-blog-post#1]
Hey, just wanted to make you aware of this: http://question2answer.org/qa/49268/notice-undefined-index-title-include-pages-admin-admin-pages

The notice is occurring because you didn't return the correct array in the `suggest_requests` function [here](https://github.com/arjunsuresh/qa-blog-post/blob/master/qa-edit.php#L38) - it needs to have a 'title' key in the array.

**Comment by arjunsuresh** [comment]
Thanks. I have corrected the issue.
